import type {
  ProgramAction,
  ProgramCategory,
  ProgramDifficulty,
  ProgramTimeOfDay,
} from "./types";

type Seed = Omit<
  ProgramAction,
  | "id"
  | "category"
  | "sourceIds"
  | "alternativeActionIds"
  | "personalizationReasons"
>;

const seeds: Record<ProgramCategory, readonly Seed[]> = {
  sleep: [
    [
      "Départ calme",
      "Choisis une heure de coucher réaliste et commence à ralentir 15 minutes avant.",
      "Un départ simple aide à rendre l’horaire plus régulier.",
      15,
      "evening",
      "beginner",
      "Tu as commencé ton temps calme avant le coucher.",
    ],
    [
      "Téléphone hors du lit",
      "Pose ton téléphone hors du lit 30 minutes avant ton heure habituelle de coucher.",
      "Réduire les écrans aide à protéger une routine du soir calme.",
      30,
      "evening",
      "beginner",
      "Le téléphone est resté hors du lit pendant le temps prévu.",
    ],
    [
      "Prépare le lendemain",
      "Prépare tes affaires pour demain avant de commencer ta routine du soir.",
      "Préparer l’environnement évite de repousser le coucher.",
      10,
      "evening",
      "beginner",
      "Tes affaires de demain sont prêtes avant la routine du soir.",
    ],
    [
      "Heure de lever stable",
      "Garde une heure de lever proche de ton horaire habituel aujourd’hui.",
      "La régularité du lever soutient un rythme de sommeil stable.",
      5,
      "morning",
      "maintenance",
      "Tu t’es levé à l’horaire prévu ou très proche.",
    ],
    [
      "Transition sans écran",
      "Remplace les écrans par une activité calme pendant les 20 dernières minutes avant le coucher.",
      "Une transition calme facilite la régularité de la routine.",
      20,
      "evening",
      "progressive",
      "Tu as fait une activité calme sans écran avant de dormir.",
    ],
    [
      "Routine en trois étapes",
      "Enchaîne toilette, affaires prêtes, puis activité calme dans le même ordre.",
      "Un ordre répétable rend le coucher plus prévisible.",
      20,
      "evening",
      "maintenance",
      "Les trois étapes ont été faites dans le même ordre.",
    ],
    [
      "Lumière du matin",
      "Ouvre les rideaux ou passe quelques minutes à la lumière du jour après le lever.",
      "Un repère du matin aide à stabiliser le rythme quotidien.",
      10,
      "morning",
      "maintenance",
      "Tu as vu la lumière du jour après ton lever.",
    ],
    [
      "Vérifie ton horaire",
      "Note si ton horaire prévu reste dans un repère adapté à ton âge, sans prolonger inutilement le temps au lit.",
      "Un repère réaliste aide à ajuster la routine avec prudence.",
      5,
      "evening",
      "progressive",
      "Tu as vérifié ton horaire sans chercher à rester au lit plus longtemps.",
    ],
    [
      "Soirée apaisée",
      "Choisis une activité calme que tu apprécies pour terminer la journée.",
      "Une fin de journée apaisée peut soutenir une routine durable.",
      15,
      "evening",
      "maintenance",
      "Tu as réalisé ton activité calme choisie.",
    ],
    [
      "Bilan de routine",
      "Repère une chose qui a facilité ton coucher et prépare-la pour demain.",
      "Le bilan permet de garder ce qui fonctionne sans perfectionnisme.",
      5,
      "evening",
      "maintenance",
      "Tu as identifié et préparé un repère utile pour demain.",
    ],
  ].map(
    ([
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    ]) => ({
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    }),
  ) as Seed[],
  activity: [
    [
      "Marche de départ",
      "Fais une marche dynamique à ton rythme dans un lieu sûr.",
      "Commencer doucement aide à construire une habitude d’activité.",
      10,
      "daytime",
      "beginner",
      "Tu as marché activement pendant le temps prévu.",
    ],
    [
      "Pause mouvement",
      "Fais une courte pause avec des mouvements simples que tu maîtrises.",
      "Les petites pauses rendent le mouvement plus accessible.",
      8,
      "daytime",
      "beginner",
      "Tu as réalisé ta pause mouvement sans douleur.",
    ],
    [
      "Activité choisie",
      "Choisis une activité que tu apprécies et bouge à une intensité confortable.",
      "Le plaisir aide à revenir à l’activité régulièrement.",
      15,
      "daytime",
      "beginner",
      "Tu as fait l’activité choisie pendant le temps prévu.",
    ],
    [
      "Mobilité douce",
      "Fais des mouvements doux de mobilité pour les épaules, hanches et chevilles.",
      "La mobilité douce peut accompagner la récupération.",
      10,
      "anytime",
      "maintenance",
      "Tu as fait les mouvements doucement et sans douleur.",
    ],
    [
      "Marche avec un proche",
      "Propose une marche ou un déplacement actif avec un proche.",
      "Le soutien social peut rendre l’activité plus régulière.",
      20,
      "daytime",
      "progressive",
      "Tu as effectué le déplacement ou la marche active.",
    ],
    [
      "Récupération active",
      "Après un entraînement, choisis une marche calme ou une mobilité légère plutôt qu’ajouter une séance intense.",
      "La récupération fait partie d’une routine équilibrée.",
      15,
      "anytime",
      "maintenance",
      "Tu as choisi une activité légère adaptée à ton état du jour.",
    ],
    [
      "Renforcement maîtrisé",
      "Fais quelques mouvements de renforcement que tu connais déjà, avec une technique contrôlée.",
      "Le renforcement peut faire partie d’une semaine variée sans surcharge.",
      15,
      "daytime",
      "progressive",
      "Tu as gardé une technique contrôlée et arrêté en cas d’inconfort.",
    ],
    [
      "Alignement confortable",
      "Pendant une activité assise ou debout, relâche les épaules et cherche une position confortable.",
      "Un bon alignement aide la manière de se tenir, sans changer les os.",
      5,
      "anytime",
      "beginner",
      "Tu as ajusté ta position de façon confortable.",
    ],
    [
      "Bouger entre deux tâches",
      "Ajoute un déplacement actif ou une courte marche entre deux tâches.",
      "Associer le mouvement à une routine existante facilite la régularité.",
      12,
      "daytime",
      "maintenance",
      "Tu as ajouté un déplacement actif à ta journée.",
    ],
    [
      "Bilan récupération",
      "Évalue ton énergie puis prépare une activité légère ou un repos actif adapté à demain.",
      "Adapter la charge à ton énergie évite de transformer chaque jour en défi intense.",
      5,
      "evening",
      "maintenance",
      "Tu as choisi une suite réaliste selon ton énergie.",
    ],
  ].map(
    ([
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    ]) => ({
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    }),
  ) as Seed[],
  nutrition: [
    [
      "Repas prévu",
      "Prévois un prochain repas complet plutôt que de le sauter.",
      "La régularité des repas soutient une routine alimentaire stable.",
      5,
      "morning",
      "beginner",
      "Tu as prévu et pris un repas aujourd’hui.",
    ],
    [
      "Eau accessible",
      "Garde de l’eau accessible et choisis d’en boire au fil de la journée.",
      "Rendre l’eau visible aide à penser à s’hydrater sans fixer de quantité individuelle.",
      2,
      "anytime",
      "beginner",
      "Tu as gardé de l’eau accessible et en as bu selon ta soif.",
    ],
    [
      "Fruit ou légume",
      "Ajoute un fruit ou un légume à l’un de tes repas ou collations.",
      "La diversité alimentaire inclut les fruits et légumes.",
      5,
      "daytime",
      "beginner",
      "Un fruit ou légume a été ajouté à un repas ou une collation.",
    ],
    [
      "Protéine alimentaire",
      "Ajoute une source alimentaire de protéines à l’un de tes repas.",
      "Les repas variés peuvent inclure des sources alimentaires de protéines.",
      5,
      "daytime",
      "maintenance",
      "Ton repas comportait une source alimentaire de protéines.",
    ],
    [
      "Assiette variée",
      "Compose un repas avec plusieurs groupes d’aliments que tu apprécies.",
      "Varier les aliments aide à construire une alimentation équilibrée.",
      10,
      "daytime",
      "maintenance",
      "Tu as choisi plusieurs groupes d’aliments pour ce repas.",
    ],
    [
      "Préparation simple",
      "Prépare ou demande une option simple pour ton prochain repas afin de ne pas l’improviser au dernier moment.",
      "Préparer une option simple aide à éviter les repas sautés.",
      10,
      "evening",
      "beginner",
      "Une option pour le prochain repas est prête ou identifiée.",
    ],
    [
      "Collation planifiée",
      "Prépare une collation simple avec un aliment fruit ou légume et un autre aliment que tu apprécies.",
      "Planifier aide à garder une routine sans restriction.",
      5,
      "daytime",
      "progressive",
      "Ta collation planifiée a été préparée ou consommée.",
    ],
    [
      "Diversité du jour",
      "Essaie un aliment ou une préparation différente parmi les options disponibles.",
      "La diversité se construit progressivement avec des choix accessibles.",
      10,
      "daytime",
      "progressive",
      "Tu as ajouté un choix différent à ta journée.",
    ],
    [
      "Repas sans écran",
      "Prends un repas ou une collation en faisant une pause des écrans.",
      "Une pause aide à remarquer ton repas et ta satiété.",
      15,
      "daytime",
      "maintenance",
      "Tu as pris ce repas ou cette collation sans écran.",
    ],
    [
      "Bilan alimentaire",
      "Repère une habitude alimentaire utile de la journée et prépare-la pour demain.",
      "Le bilan aide à consolider une routine réaliste.",
      5,
      "evening",
      "maintenance",
      "Tu as choisi une habitude à garder demain.",
    ],
  ].map(
    ([
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    ]) => ({
      title,
      instruction,
      reason,
      durationMinutes,
      timeOfDay,
      difficulty,
      completionCriteria,
    }),
  ) as Seed[],
};

const sourceFor: Record<ProgramCategory, string> = {
  sleep: "aasm-sleep-2016",
  activity: "who-physical-activity",
  nutrition: "who-healthy-diet",
};

export const ACTION_CATALOG: readonly ProgramAction[] = (
  Object.keys(seeds) as ProgramCategory[]
).flatMap((category) =>
  seeds[category].map((seed, index, categorySeeds) => ({
    ...seed,
    id: `${category}-${index + 1}`,
    category,
    sourceIds: [sourceFor[category]],
    alternativeActionIds: [1, 2, 3].map(
      (offset) =>
        `${category}-${((index + offset) % categorySeeds.length) + 1}`,
    ),
    personalizationReasons: [],
  })),
);

export const ACTIONS_BY_ID = new Map(
  ACTION_CATALOG.map((action) => [action.id, action]),
);
